apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    labbox-pod-name: {{ name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      labbox-pod-name: {{ name }}
  template:
    metadata:
      labels:
        labbox-pod-name: {{ name }}
    spec:
      restartPolicy: Always
      {% if server %}
      nodeSelector:
        kubernetes.io/hostname: {{ server }}
      {% endif %}
      containers:
        - name: main
          image: {{ image }}
          ports:
            - containerPort: 22
            - containerPort: 6080
            - containerPort: 8000
          env:
            - name: USERNAME
              value: {{ username }}
            - name: PASSWORD
              value: {{ password }}
            - name: POD_NAME
              value: {{ name }}
          
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: nfs-nas-personal
              mountPath: /home/{{ username}}
              subPath: user_home_dir/{{ lab }}/{{ username }}/{{ version }}
            {% if lab == 'Toolmen' %}
            - name: nfs-nas-data
              mountPath: /home/nas  
            - name: nfs-nas-data2
              mountPath: /home/nas2
            - name: nfs-nas-pig
              mountPath: /home/nas-pig 
            {% endif %}
            {% if lab == 'BBLAB' %}
            - name: nfs-nas405-data 
              mountPath: /home/nas  
            {% endif %}
            {% if lab == 'Tsukuba' %}
            - name: nfs-tsukuba  
              mountPath: /home/nas  
            {% endif %}
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "60Gi"
      
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: nfs-nas-personal
          persistentVolumeClaim:
            claimName: nfs-nas-personal
        {% if lab == 'Toolmen' %}
        - name: nfs-nas-data
          persistentVolumeClaim:
            claimName: nfs-nas-data
        - name: nfs-nas-data2
          persistentVolumeClaim:
            claimName: nfs-nas-data2
        - name: nfs-nas-pig
          persistentVolumeClaim:
            claimName: nfs-nas-pig
        {% endif %}
        {% if lab == 'BBLAB' %}
        - name: nfs-nas405-data 
          persistentVolumeClaim:
            claimName: nfs-nas405-data 
        {% endif %}
        {% if lab == 'Tsukuba' %}
        - name: nfs-tsukuba  
          persistentVolumeClaim:
            claimName: nfs-tsukuba  
        {% endif %}

