apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
spec:
  selector:
    labbox-pod-name: {{ name }}
  ports:
  - name: ssh-22
    protocol: TCP
    port: 22
    targetPort: 22
  - name: tcp-6080
    protocol: TCP
    port: 6080
    targetPort: 6080
  - name: tcp-8000
    protocol: TCP
    port: 8000
    targetPort: 8000