apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: "ml.toolmenlab.bime.ntu.edu.tw"
    http:
      paths:
      - path: "/{{ name }}"
        pathType: "Prefix"
        backend:
          service:
            name: {{ name }}
            port: 
              number: 8080